# Generated by Django 4.2.17 on 2025-01-17 18:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
