# Generated by Django 4.2.17 on 2025-01-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_portfolio_portfolio_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instagram_link',
        ),
    ]
