# Generated by Django 4.2.17 on 2026-02-14 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfolio_app", "0009_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter / X"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        default="phone",
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Optional label, e.g. "Work", "Personal"',
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["contact_type", "id"],
            },
        ),
    ]
