# Generated by Django 4.2.17 on 2026-02-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0012_customdomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdomain",
            name="zone_id",
            field=models.CharField(
                blank=True, help_text="Cloudflare zone ID", max_length=100, null=True
            ),
        ),
    ]
