# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_customdomain_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='name_servers',
            field=models.JSONField(blank=True, default=list, help_text='Stored nameservers from Cloudflare'),
        ),
    ]
